server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  h2:
   console:
     enabled: true
  application:
    name: submarine-managment     
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
